using Grpc.Core;

namespace Control.Services;

public class ConnectedAgent
{
    private ConnectedAgent(string id, DateTime at, IServerStreamWriter<ControlCommand> commandStream)
    {
        Id = id;
        ConnectedAt = at;
        CommandStream = commandStream;
    }

    public static ConnectedAgent CreateInstance(AgentHandshake handshake, IServerStreamWriter<ControlCommand> commandStream)
    {
        // AgentId is generated by the agent client and passed in the handshake
        var id = handshake.Id;
        var at = DateTime.UtcNow;
        return new ConnectedAgent(id, at, commandStream);
    }

    public string Id { get; }
    
    public DateTime ConnectedAt { get; }
    
    public IServerStreamWriter<ControlCommand> CommandStream { get; }
}