# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish macOS ARM64
      run: dotnet publish src/Agent/Agent.csproj -c Release -r osx-arm64 --self-contained true -o artifacts/osx-arm64
  
    - name: Publish macOS x64 (Intel)
      run: dotnet publish src/Agent/Agent.csproj -c Release -r osx-x64 --self-contained true -o artifacts/osx-x64
