name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    # macOS ARM64
    - name: Publish macOS arm64
      run: dotnet publish src/Agent/Agent.csproj -c Release -r osx-arm64 --self-contained true -o artifacts/macos/arm64

    - name: Upload macOS arm64
      uses: actions/upload-artifact@v4
      with:
        name: agent-macos-arm64
        path: artifacts/macos/arm64
      
    # macOS x64
    - name: Publish macOS x64
      run: dotnet publish src/Agent/Agent.csproj -c Release -r osx-x64 --self-contained true -o artifacts/macos/x64

    - name: Upload macOS x64
      uses: actions/upload-artifact@v4
      with:
        name: agent-macos-x64
        path: artifacts/macos/x64
      
    # Linux x64
    - name: Publish linux x64
      run: dotnet publish src/Agent/Agent.csproj -c Release -r linux-x64 --self-contained true -o artifacts/linux/x64

    - name: Upload linux x64
      uses: actions/upload-artifact@v4
      with:
        name: agent-linux-x64
        path: artifacts/linux/x64
      
    # Windows x64
    - name: Publish windows x64
      run: dotnet publish src/Agent/Agent.csproj -c Release -r win-x64 --self-contained true -o artifacts/windows/x64

    - name: Upload windows x64
      uses: actions/upload-artifact@v4
      with:
        name: agent-windows-x64
        path: artifacts/windows/x64